### PR TITLE
Update Nheko proposals to 2021

### PR DESCRIPTION
**Pull request by deepbluev7**
This is still a bit WIP, I want @redsky17 to review it first, but this is the current draft and we are working on it!

### CODE REVIEW

**Comment by redsky17** [comment]
@deepbluev7 I made some updates.  Let me know what you think.

**Comment by deepbluev7** [comment]
Looks good to me!

**Review by benparsons — APPROVED** [review]
lgtm

**Comment by deepbluev7** [comment]
Thank you!

**Pull request merged**
